/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activité/': RouteRecordInfo<'/activité/', '/activité', Record<never, never>, Record<never, never>>,
    '/carte/': RouteRecordInfo<'/carte/', '/carte', Record<never, never>, Record<never, never>>,
    '/coaching/': RouteRecordInfo<'/coaching/', '/coaching', Record<never, never>, Record<never, never>>,
    '/compte/': RouteRecordInfo<'/compte/', '/compte', Record<never, never>, Record<never, never>>,
    '/compte/abonnement': RouteRecordInfo<'/compte/abonnement', '/compte/abonnement', Record<never, never>, Record<never, never>>,
    '/compte/avis': RouteRecordInfo<'/compte/avis', '/compte/avis', Record<never, never>, Record<never, never>>,
    '/compte/conditionsgenerales': RouteRecordInfo<'/compte/conditionsgenerales', '/compte/conditionsgenerales', Record<never, never>, Record<never, never>>,
    '/compte/donnéespersonnelles': RouteRecordInfo<'/compte/donnéespersonnelles', '/compte/donnéespersonnelles', Record<never, never>, Record<never, never>>,
    '/compte/langue': RouteRecordInfo<'/compte/langue', '/compte/langue', Record<never, never>, Record<never, never>>,
    '/compte/paiement': RouteRecordInfo<'/compte/paiement', '/compte/paiement', Record<never, never>, Record<never, never>>,
    '/compte/personnesrencontrées': RouteRecordInfo<'/compte/personnesrencontrées', '/compte/personnesrencontrées', Record<never, never>, Record<never, never>>,
    '/compte/politiquesconfidentialité': RouteRecordInfo<'/compte/politiquesconfidentialité', '/compte/politiquesconfidentialité', Record<never, never>, Record<never, never>>,
    '/compte/settings': RouteRecordInfo<'/compte/settings', '/compte/settings', Record<never, never>, Record<never, never>>,
    '/message/': RouteRecordInfo<'/message/', '/message', Record<never, never>, Record<never, never>>,
    '/Notification/': RouteRecordInfo<'/Notification/', '/Notification', Record<never, never>, Record<never, never>>,
  }
}
