/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activité/': RouteRecordInfo<'/activité/', '/activité', Record<never, never>, Record<never, never>>,
    '/activité/[id]': RouteRecordInfo<'/activité/[id]', '/activité/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/activité/CreationActivité': RouteRecordInfo<'/activité/CreationActivité', '/activité/CreationActivité', Record<never, never>, Record<never, never>>,
    '/activité/CreationGroupe': RouteRecordInfo<'/activité/CreationGroupe', '/activité/CreationGroupe', Record<never, never>, Record<never, never>>,
    '/activité/felicitation': RouteRecordInfo<'/activité/felicitation', '/activité/felicitation', Record<never, never>, Record<never, never>>,
    '/activité/Filtre': RouteRecordInfo<'/activité/Filtre', '/activité/Filtre', Record<never, never>, Record<never, never>>,
    '/activité/Groupe': RouteRecordInfo<'/activité/Groupe', '/activité/Groupe', Record<never, never>, Record<never, never>>,
    '/activité/RDV': RouteRecordInfo<'/activité/RDV', '/activité/RDV', Record<never, never>, Record<never, never>>,
    '/activité/recherche': RouteRecordInfo<'/activité/recherche', '/activité/recherche', Record<never, never>, Record<never, never>>,
    '/carte/': RouteRecordInfo<'/carte/', '/carte', Record<never, never>, Record<never, never>>,
    '/coaching/': RouteRecordInfo<'/coaching/', '/coaching', Record<never, never>, Record<never, never>>,
    '/coaching/[id]': RouteRecordInfo<'/coaching/[id]', '/coaching/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/coaching/contact': RouteRecordInfo<'/coaching/contact', '/coaching/contact', Record<never, never>, Record<never, never>>,
    '/coaching/DevenirCoach': RouteRecordInfo<'/coaching/DevenirCoach', '/coaching/DevenirCoach', Record<never, never>, Record<never, never>>,
    '/coaching/felicitation': RouteRecordInfo<'/coaching/felicitation', '/coaching/felicitation', Record<never, never>, Record<never, never>>,
    '/coaching/felicitationCoach': RouteRecordInfo<'/coaching/felicitationCoach', '/coaching/felicitationCoach', Record<never, never>, Record<never, never>>,
    '/coaching/recherche': RouteRecordInfo<'/coaching/recherche', '/coaching/recherche', Record<never, never>, Record<never, never>>,
    '/compte/': RouteRecordInfo<'/compte/', '/compte', Record<never, never>, Record<never, never>>,
    '/compte/CompteAbonnement': RouteRecordInfo<'/compte/CompteAbonnement', '/compte/CompteAbonnement', Record<never, never>, Record<never, never>>,
    '/compte/CompteAvis': RouteRecordInfo<'/compte/CompteAvis', '/compte/CompteAvis', Record<never, never>, Record<never, never>>,
    '/compte/CompteCG': RouteRecordInfo<'/compte/CompteCG', '/compte/CompteCG', Record<never, never>, Record<never, never>>,
    '/compte/CompteDP': RouteRecordInfo<'/compte/CompteDP', '/compte/CompteDP', Record<never, never>, Record<never, never>>,
    '/compte/CompteLangue': RouteRecordInfo<'/compte/CompteLangue', '/compte/CompteLangue', Record<never, never>, Record<never, never>>,
    '/compte/ComptePaiement': RouteRecordInfo<'/compte/ComptePaiement', '/compte/ComptePaiement', Record<never, never>, Record<never, never>>,
    '/compte/ComptePC': RouteRecordInfo<'/compte/ComptePC', '/compte/ComptePC', Record<never, never>, Record<never, never>>,
    '/compte/ComptePersonneRencontré': RouteRecordInfo<'/compte/ComptePersonneRencontré', '/compte/ComptePersonneRencontré', Record<never, never>, Record<never, never>>,
    '/connexion': RouteRecordInfo<'/connexion', '/connexion', Record<never, never>, Record<never, never>>,
    '/inscription/': RouteRecordInfo<'/inscription/', '/inscription', Record<never, never>, Record<never, never>>,
    '/inscription/config': RouteRecordInfo<'/inscription/config', '/inscription/config', Record<never, never>, Record<never, never>>,
    '/message/Message-Index': RouteRecordInfo<'/message/Message-Index', '/message/Message-Index', Record<never, never>, Record<never, never>>,
    '/Notification/NotifIndex': RouteRecordInfo<'/Notification/NotifIndex', '/Notification/NotifIndex', Record<never, never>, Record<never, never>>,
    '/SeConnecter': RouteRecordInfo<'/SeConnecter', '/SeConnecter', Record<never, never>, Record<never, never>>,
  }
}
